openapi: 3.1.0
info:
  title: API de Carrito de Compras
  version: 1.0.0
paths:
  /api/cart:
    get:
      summary: Obtener todos los carritos
      tags:
        - Carrito de Compras
      responses:
        "200":
          description: Lista de carritos obtenida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cart"
    post:
      summary: Crear un nuevo carrito
      tags:
        - Carrito de Compras
      responses:
        "201":
          description: Carrito creado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
  /api/cart/{cid}:
    get:
      summary: Obtener un carrito por ID
      tags:
        - Carrito de Compras
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito a obtener
          schema:
            type: string
      responses:
        "200":
          description: Carrito encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "404":
          description: Carrito no encontrado
    put:
      summary: Actualizar un carrito por ID
      tags:
        - Carrito de Compras
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito a actualizar
          schema:
            type: string
      responses:
        "200":
          description: Carrito actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "404":
          description: Carrito no encontrado
    delete:
      summary: Eliminar un carrito por ID
      tags:
        - Carrito de Compras
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito a eliminar
          schema:
            type: string
      responses:
        "204":
          description: Carrito eliminado exitosamente
        "404":
          description: Carrito no encontrado
  /api/cart/{cid}/product/{productId}:
    post:
      summary: Agregar un producto al carrito
      tags:
        - Carrito de Compras
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito al que se agrega el producto
          schema:
            type: string
        - name: productId
          in: path
          required: true
          description: ID del producto a agregar al carrito
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: number
      responses:
        "200":
          description: Producto agregado al carrito exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "400":
          description: Solicitud incorrecta
        "403":
          description: No tienes permisos para agregar productos al carrito
        "404":
          description: Carrito o producto no encontrado
    delete:
      summary: Eliminar un producto del carrito
      tags:
        - Carrito de Compras
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito del que se elimina el producto
          schema:
            type: string
        - name: productId
          in: path
          required: true
          description: ID del producto a eliminar del carrito
          schema:
            type: string
      responses:
        "204":
          description: Producto eliminado del carrito exitosamente
        "404":
          description: Carrito o producto no encontrado
  /api/cart/{cid}/purchase:
    post:
      summary: Realizar compra desde el carrito
      tags:
        - Carrito de Compras
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito desde el cual se realiza la compra
          schema:
            type: string
      responses:
        "200":
          description: Compra realizada exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ticket"
        "400":
          description: El carrito está vacío o hay problemas con los productos
        "404":
          description: Carrito no encontrado
        "500":
          description: Error del servidor
components:
  schemas:
    Cart:
      type: object
      description: Información sobre un carrito de compras.
      properties:
        _id:
          type: string
          description: ID del carrito.
        products:
          type: array
          description: Lista de productos en el carrito.
          items:
            type: object
            properties:
              productId:
                type: string
                description: ID del producto.
              quantity:
                type: number
                description: Cantidad del producto en el carrito.
    Ticket:
      type: object
      description: Información sobre un ticket de compra.
      properties:
        code:
          type: string
          description: Código del ticket.
        purchase_datetime:
          type: string
          description: Fecha y hora de la compra.
        amount:
          type: number
          description: Monto total de la compra.
security:
  - roleAuth: ['user', 'premium']

